version: '3.8'

services:
  # Single container with both Frontend + Backend
  app:
    build:
      context: .
      dockerfile: Dockerfile.combined
    container_name: admin-dashboard-app
    restart: unless-stopped
    ports:
      - "3000:3000"  # Frontend
      - "5000:5000"  # Backend
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
      # Supabase credentials
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # Email configuration (optional)
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      # React environment
      - REACT_APP_API_URL=http://localhost:5000/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    stdin_open: true
    tty: true

