-- Migration: Create Vapi_accounts table
-- Description: Creates a table to store Vapi account information
-- Date: 2024

-- Create Vapi_accounts table
CREATE TABLE IF NOT EXISTS public."Vapi_accounts" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "Account_name" TEXT NOT NULL,
  "Account_description" TEXT NULL,
  CONSTRAINT Vapi_accounts_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_vapi_accounts_account_name ON public."Vapi_accounts"("Account_name");

-- Add comments
COMMENT ON TABLE public."Vapi_accounts" IS 'Stores Vapi account information';
COMMENT ON COLUMN public."Vapi_accounts".id IS 'Unique identifier for the Vapi account';
COMMENT ON COLUMN public."Vapi_accounts"."Account_name" IS 'Name of the Vapi account';
COMMENT ON COLUMN public."Vapi_accounts"."Account_description" IS 'Description of the Vapi account';

