// Country data with flags (emoji) and phone codes
export const countries = [
  { name: "Afghanistan", code: "AF", flag: "🇦🇫", phoneCode: "+93", totalLength: 12 },
  { name: "Albania", code: "AL", flag: "🇦🇱", phoneCode: "+355", totalLength: 12 },
  { name: "Algeria", code: "DZ", flag: "🇩🇿", phoneCode: "+213", totalLength: 12 },
  { name: "Andorra", code: "AD", flag: "🇦🇩", phoneCode: "+376", totalLength: 12 },
  { name: "Angola", code: "AO", flag: "🇦🇴", phoneCode: "+244", totalLength: 12 },
  { name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬", phoneCode: "+1-268", totalLength: 11 },
  { name: "Argentina", code: "AR", flag: "🇦🇷", phoneCode: "+54", totalLength: 13 },
  { name: "Armenia", code: "AM", flag: "🇦🇲", phoneCode: "+374", totalLength: 11 },
  { name: "Australia", code: "AU", flag: "🇦🇺", phoneCode: "+61", totalLength: 11 },
  { name: "Austria", code: "AT", flag: "🇦🇹", phoneCode: "+43", totalLength: 13 },
  { name: "Azerbaijan", code: "AZ", flag: "🇦🇿", phoneCode: "+994", totalLength: 12 },
  { name: "Bahamas", code: "BS", flag: "🇧🇸", phoneCode: "+1-242", totalLength: 11 },
  { name: "Bahrain", code: "BH", flag: "🇧🇭", phoneCode: "+973", totalLength: 11 },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩", phoneCode: "+880", totalLength: 13 },
  { name: "Barbados", code: "BB", flag: "🇧🇧", phoneCode: "+1-246", totalLength: 11 },
  { name: "Belarus", code: "BY", flag: "🇧🇾", phoneCode: "+375", totalLength: 12 },
  { name: "Belgium", code: "BE", flag: "🇧🇪", phoneCode: "+32", totalLength: 12 },
  { name: "Belize", code: "BZ", flag: "🇧🇿", phoneCode: "+501", totalLength: 11 },
  { name: "Benin", code: "BJ", flag: "🇧🇯", phoneCode: "+229", totalLength: 12 },
  { name: "Bhutan", code: "BT", flag: "🇧🇹", phoneCode: "+975", totalLength: 11 },
  { name: "Bolivia", code: "BO", flag: "🇧🇴", phoneCode: "+591", totalLength: 12 },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦", phoneCode: "+387", totalLength: 12 },
  { name: "Botswana", code: "BW", flag: "🇧🇼", phoneCode: "+267", totalLength: 11 },
  { name: "Brazil", code: "BR", flag: "🇧🇷", phoneCode: "+55", totalLength: 13 },
  { name: "Brunei", code: "BN", flag: "🇧🇳", phoneCode: "+673", totalLength: 11 },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬", phoneCode: "+359", totalLength: 13 },
  { name: "Burkina Faso", code: "BF", flag: "🇧🇫", phoneCode: "+226", totalLength: 12 },
  { name: "Burundi", code: "BI", flag: "🇧🇮", phoneCode: "+257", totalLength: 11 },
  { name: "Cabo Verde", code: "CV", flag: "🇨🇻", phoneCode: "+238", totalLength: 11 },
  { name: "Cambodia", code: "KH", flag: "🇰🇭", phoneCode: "+855", totalLength: 12 },
  { name: "Cameroon", code: "CM", flag: "🇨🇲", phoneCode: "+237", totalLength: 12 },
  { name: "Canada", code: "CA", flag: "🇨🇦", phoneCode: "+1", totalLength: 11 },
  { name: "Central African Republic", code: "CF", flag: "🇨🇫", phoneCode: "+236", totalLength: 11 },
  { name: "Chad", code: "TD", flag: "🇹🇩", phoneCode: "+235", totalLength: 11 },
  { name: "Chile", code: "CL", flag: "🇨🇱", phoneCode: "+56", totalLength: 12 },
  { name: "China", code: "CN", flag: "🇨🇳", phoneCode: "+86", totalLength: 13 },
  { name: "Colombia", code: "CO", flag: "🇨🇴", phoneCode: "+57", totalLength: 13 },
  { name: "Comoros", code: "KM", flag: "🇰🇲", phoneCode: "+269", totalLength: 11 },
  { name: "Congo (Democratic Rep. of the)", code: "CD", flag: "🇨🇩", phoneCode: "+243", totalLength: 12 },
  { name: "Congo (Rep. of the)", code: "CG", flag: "🇨🇬", phoneCode: "+242", totalLength: 11 },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷", phoneCode: "+506", totalLength: 11 },
  { name: "Côte d'Ivoire", code: "CI", flag: "🇨🇮", phoneCode: "+225", totalLength: 12 },
  { name: "Croatia", code: "HR", flag: "🇭🇷", phoneCode: "+385", totalLength: 12 },
  { name: "Cuba", code: "CU", flag: "🇨🇺", phoneCode: "+53", totalLength: 12 },
  { name: "Cyprus", code: "CY", flag: "🇨🇾", phoneCode: "+357", totalLength: 10 },
  { name: "Czechia (Czech Republic)", code: "CZ", flag: "🇨🇿", phoneCode: "+420", totalLength: 13 },
  { name: "Denmark", code: "DK", flag: "🇩🇰", phoneCode: "+45", totalLength: 11 },
  { name: "Djibouti", code: "DJ", flag: "🇩🇯", phoneCode: "+253", totalLength: 11 },
  { name: "Dominica", code: "DM", flag: "🇩🇲", phoneCode: "+1-767", totalLength: 11 },
  { name: "Dominican Republic", code: "DO", flag: "🇩🇴", phoneCode: "+1-809, +1-829, +1-849", totalLength: 11 },
  { name: "Ecuador", code: "EC", flag: "🇪🇨", phoneCode: "+593", totalLength: 12 },
  { name: "Egypt", code: "EG", flag: "🇪🇬", phoneCode: "+20", totalLength: 12 },
  { name: "El Salvador", code: "SV", flag: "🇸🇻", phoneCode: "+503", totalLength: 11 },
  { name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶", phoneCode: "+240", totalLength: 12 },
  { name: "Eritrea", code: "ER", flag: "🇪🇷", phoneCode: "+291", totalLength: 11 },
  { name: "Estonia", code: "EE", flag: "🇪🇪", phoneCode: "+372", totalLength: 12 },
  { name: "Eswatini", code: "SZ", flag: "🇸🇿", phoneCode: "+268", totalLength: 11 },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹", phoneCode: "+251", totalLength: 12 },
  { name: "Fiji", code: "FJ", flag: "🇫🇯", phoneCode: "+679", totalLength: 10 },
  { name: "Finland", code: "FI", flag: "🇫🇮", phoneCode: "+358", totalLength: 12 },
  { name: "France", code: "FR", flag: "🇫🇷", phoneCode: "+33", totalLength: 11 },
  { name: "Gabon", code: "GA", flag: "🇬🇦", phoneCode: "+241", totalLength: 11 },
  { name: "Gambia", code: "GM", flag: "🇬🇲", phoneCode: "+220", totalLength: 10 },
  { name: "Georgia", code: "GE", flag: "🇬🇪", phoneCode: "+995", totalLength: 12 },
  { name: "Germany", code: "DE", flag: "🇩🇪", phoneCode: "+49", totalLength: 13 },
  { name: "Ghana", code: "GH", flag: "🇬🇭", phoneCode: "+233", totalLength: 12 },
  { name: "Greece", code: "GR", flag: "🇬🇷", phoneCode: "+30", totalLength: 13 },
  { name: "Grenada", code: "GD", flag: "🇬🇩", phoneCode: "+1-473", totalLength: 11 },
  { name: "Guatemala", code: "GT", flag: "🇬🇹", phoneCode: "+502", totalLength: 11 },
  { name: "Guinea", code: "GN", flag: "🇬🇳", phoneCode: "+224", totalLength: 11 },
  { name: "Guinea-Bissau", code: "GW", flag: "🇬🇼", phoneCode: "+245", totalLength: 10 },
  { name: "Guyana", code: "GY", flag: "🇬🇾", phoneCode: "+592", totalLength: 10 },
  { name: "Haiti", code: "HT", flag: "🇭🇹", phoneCode: "+509", totalLength: 11 },
  { name: "Holy See (Vatican City)", code: "VA", flag: "🇻🇦", phoneCode: "+379", totalLength: 9 },
  { name: "Honduras", code: "HN", flag: "🇭🇳", phoneCode: "+504", totalLength: 12 },
  { name: "Hungary", code: "HU", flag: "🇭🇺", phoneCode: "+36", totalLength: 11 },
  { name: "Iceland", code: "IS", flag: "🇮🇸", phoneCode: "+354", totalLength: 11 },
  { name: "India", code: "IN", flag: "🇮🇳", phoneCode: "+91", totalLength: 12 },
  { name: "Indonesia", code: "ID", flag: "🇮🇩", phoneCode: "+62", totalLength: 12 },
  { name: "Iran", code: "IR", flag: "🇮🇷", phoneCode: "+98", totalLength: 12 },
  { name: "Iraq", code: "IQ", flag: "🇮🇶", phoneCode: "+964", totalLength: 13 },
  { name: "Ireland", code: "IE", flag: "🇮🇪", phoneCode: "+353", totalLength: 12 },
  { name: "Israel", code: "IL", flag: "🇮🇱", phoneCode: "+972", totalLength: 13 },
  { name: "Italy", code: "IT", flag: "🇮🇹", phoneCode: "+39", totalLength: 13 },
  { name: "Jamaica", code: "JM", flag: "🇯🇲", phoneCode: "+1-876", totalLength: 11 },
  { name: "Japan", code: "JP", flag: "🇯🇵", phoneCode: "+81", totalLength: 12 },
  { name: "Jordan", code: "JO", flag: "🇯🇴", phoneCode: "+962", totalLength: 12 },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿", phoneCode: "+7", totalLength: 11 },
  { name: "Kenya", code: "KE", flag: "🇰🇪", phoneCode: "+254", totalLength: 12 },
  { name: "Kiribati", code: "KI", flag: "🇰🇮", phoneCode: "+686", totalLength: 8 },
  { name: "Korea (DPR - North)", code: "KP", flag: "🇰🇵", phoneCode: "+850", totalLength: 11 },
  { name: "Korea (Republic of - South)", code: "KR", flag: "🇰🇷", phoneCode: "+82", totalLength: 11 },
  { name: "Kuwait", code: "KW", flag: "🇰🇼", phoneCode: "+965", totalLength: 11 },
  { name: "Kyrgyzstan", code: "KG", flag: "🇰🇬", phoneCode: "+996", totalLength: 12 },
  { name: "Laos", code: "LA", flag: "🇱🇦", phoneCode: "+856", totalLength: 10 },
  { name: "Latvia", code: "LV", flag: "🇱🇻", phoneCode: "+371", totalLength: 11 },
  { name: "Lebanon", code: "LB", flag: "🇱🇧", phoneCode: "+961", totalLength: 11 },
  { name: "Lesotho", code: "LS", flag: "🇱🇸", phoneCode: "+266", totalLength: 12 },
  { name: "Liberia", code: "LR", flag: "🇱🇷", phoneCode: "+231", totalLength: 11 },
  { name: "Libya", code: "LY", flag: "🇱🇾", phoneCode: "+218", totalLength: 12 },
  { name: "Liechtenstein", code: "LI", flag: "🇱🇮", phoneCode: "+423", totalLength: 12 },
  { name: "Lithuania", code: "LT", flag: "🇱🇹", phoneCode: "+370", totalLength: 12 },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺", phoneCode: "+352", totalLength: 12 },
  { name: "Madagascar", code: "MG", flag: "🇲🇬", phoneCode: "+261", totalLength: 12 },
  { name: "Malawi", code: "MW", flag: "🇲🇼", phoneCode: "+265", totalLength: 12 },
  { name: "Malaysia", code: "MY", flag: "🇲🇾", phoneCode: "+60", totalLength: 11 },
  { name: "Maldives", code: "MV", flag: "🇲🇻", phoneCode: "+960", totalLength: 10 },
  { name: "Mali", code: "ML", flag: "🇲🇱", phoneCode: "+223", totalLength: 11 },
  { name: "Malta", code: "MT", flag: "🇲🇹", phoneCode: "+356", totalLength: 11 },
  { name: "Marshall Islands", code: "MH", flag: "🇲🇭", phoneCode: "+692", totalLength: 7 },
  { name: "Mauritania", code: "MR", flag: "🇲🇷", phoneCode: "+222", totalLength: 11 },
  { name: "Mauritius", code: "MU", flag: "🇲🇺", phoneCode: "+230", totalLength: 10 },
  { name: "Mexico", code: "MX", flag: "🇲🇽", phoneCode: "+52", totalLength: 13 },
  { name: "Micronesia (Federated States of)", code: "FM", flag: "🇫🇲", phoneCode: "+691", totalLength: 7 },
  { name: "Moldova", code: "MD", flag: "🇲🇩", phoneCode: "+373", totalLength: 12 },
  { name: "Monaco", code: "MC", flag: "🇲🇨", phoneCode: "+377", totalLength: 11 },
  { name: "Mongolia", code: "MN", flag: "🇲🇳", phoneCode: "+976", totalLength: 12 },
  { name: "Montenegro", code: "ME", flag: "🇲🇪", phoneCode: "+382", totalLength: 12 },
  { name: "Morocco", code: "MA", flag: "🇲🇦", phoneCode: "+212", totalLength: 12 },
  { name: "Mozambique", code: "MZ", flag: "🇲🇿", phoneCode: "+258", totalLength: 12 },
  { name: "Myanmar", code: "MM", flag: "🇲🇲", phoneCode: "+95", totalLength: 11 },
  { name: "Namibia", code: "NA", flag: "🇳🇦", phoneCode: "+264", totalLength: 11 },
  { name: "Nauru", code: "NR", flag: "🇳🇷", phoneCode: "+674", totalLength: 7 },
  { name: "Nepal", code: "NP", flag: "🇳🇵", phoneCode: "+977", totalLength: 10 },
  { name: "Netherlands", code: "NL", flag: "🇳🇱", phoneCode: "+31", totalLength: 11 },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿", phoneCode: "+64", totalLength: 11 },
  { name: "Nicaragua", code: "NI", flag: "🇳🇮", phoneCode: "+505", totalLength: 12 },
  { name: "Niger", code: "NE", flag: "🇳🇪", phoneCode: "+227", totalLength: 11 },
  { name: "Nigeria", code: "NG", flag: "🇳🇬", phoneCode: "+234", totalLength: 13 },
  { name: "North Macedonia", code: "MK", flag: "🇲🇰", phoneCode: "+389", totalLength: 12 },
  { name: "Norway", code: "NO", flag: "🇳🇴", phoneCode: "+47", totalLength: 10 },
  { name: "Oman", code: "OM", flag: "🇴🇲", phoneCode: "+968", totalLength: 11 },
  { name: "Pakistan", code: "PK", flag: "🇵🇰", phoneCode: "+92", totalLength: 12 },
  { name: "Palau", code: "PW", flag: "🇵🇼", phoneCode: "+680", totalLength: 7 },
  { name: "Palestine", code: "PS", flag: "🇵🇸", phoneCode: "+970", totalLength: 12 },
  { name: "Panama", code: "PA", flag: "🇵🇦", phoneCode: "+507", totalLength: 11 },
  { name: "Papua New Guinea", code: "PG", flag: "🇵🇬", phoneCode: "+675", totalLength: 11 },
  { name: "Paraguay", code: "PY", flag: "🇵🇾", phoneCode: "+595", totalLength: 12 },
  { name: "Peru", code: "PE", flag: "🇵🇪", phoneCode: "+51", totalLength: 12 },
  { name: "Philippines", code: "PH", flag: "🇵🇭", phoneCode: "+63", totalLength: 12 },
  { name: "Poland", code: "PL", flag: "🇵🇱", phoneCode: "+48", totalLength: 12 },
  { name: "Portugal", code: "PT", flag: "🇵🇹", phoneCode: "+351", totalLength: 12 },
  { name: "Qatar", code: "QA", flag: "🇶🇦", phoneCode: "+974", totalLength: 11 },
  { name: "Romania", code: "RO", flag: "🇷🇴", phoneCode: "+40", totalLength: 12 },
  { name: "Russia", code: "RU", flag: "🇷🇺", phoneCode: "+7", totalLength: 11 },
  { name: "Rwanda", code: "RW", flag: "🇷🇼", phoneCode: "+250", totalLength: 12 },
  { name: "Saint Kitts and Nevis", code: "KN", flag: "🇰🇳", phoneCode: "+1-869", totalLength: 11 },
  { name: "Saint Lucia", code: "LC", flag: "🇱🇨", phoneCode: "+1-758", totalLength: 11 },
  { name: "Saint Vincent and the Grenadines", code: "VC", flag: "🇻🇨", phoneCode: "+1-784", totalLength: 11 },
  { name: "Samoa", code: "WS", flag: "🇼🇸", phoneCode: "+685", totalLength: 8 },
  { name: "San Marino", code: "SM", flag: "🇸🇲", phoneCode: "+378", totalLength: 10 },
  { name: "Sao Tome and Principe", code: "ST", flag: "🇸🇹", phoneCode: "+239", totalLength: 9 },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦", phoneCode: "+966", totalLength: 12 },
  { name: "Senegal", code: "SN", flag: "🇸🇳", phoneCode: "+221", totalLength: 12 },
  { name: "Serbia", code: "RS", flag: "🇷🇸", phoneCode: "+381", totalLength: 12 },
  { name: "Seychelles", code: "SC", flag: "🇸🇨", phoneCode: "+248", totalLength: 10 },
  { name: "Sierra Leone", code: "SL", flag: "🇸🇱", phoneCode: "+232", totalLength: 11 },
  { name: "Singapore", code: "SG", flag: "🇸🇬", phoneCode: "+65", totalLength: 10 },
  { name: "Slovakia", code: "SK", flag: "🇸🇰", phoneCode: "+421", totalLength: 12 },
  { name: "Slovenia", code: "SI", flag: "🇸🇮", phoneCode: "+386", totalLength: 11 },
  { name: "Solomon Islands", code: "SB", flag: "🇸🇧", phoneCode: "+677", totalLength: 10 },
  { name: "Somalia", code: "SO", flag: "🇸🇴", phoneCode: "+252", totalLength: 9 },
  { name: "South Africa", code: "ZA", flag: "🇿🇦", phoneCode: "+27", totalLength: 11 },
  { name: "South Sudan", code: "SS", flag: "🇸🇸", phoneCode: "+211", totalLength: 12 },
  { name: "Spain", code: "ES", flag: "🇪🇸", phoneCode: "+34", totalLength: 12 },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰", phoneCode: "+94", totalLength: 11 },
  { name: "Sudan", code: "SD", flag: "🇸🇩", phoneCode: "+249", totalLength: 12 },
  { name: "Suriname", code: "SR", flag: "🇸🇷", phoneCode: "+597", totalLength: 11 },
  { name: "Sweden", code: "SE", flag: "🇸🇪", phoneCode: "+46", totalLength: 12 },
  { name: "Switzerland", code: "CH", flag: "🇨🇭", phoneCode: "+41", totalLength: 11 },
  { name: "Syria", code: "SY", flag: "🇸🇾", phoneCode: "+963", totalLength: 12 },
  { name: "Tajikistan", code: "TJ", flag: "🇹🇯", phoneCode: "+992", totalLength: 12 },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿", phoneCode: "+255", totalLength: 12 },
  { name: "Thailand", code: "TH", flag: "🇹🇭", phoneCode: "+66", totalLength: 11 },
  { name: "Timor-Leste", code: "TL", flag: "🇹🇱", phoneCode: "+670", totalLength: 9 },
  { name: "Togo", code: "TG", flag: "🇹🇬", phoneCode: "+228", totalLength: 10 },
  { name: "Tonga", code: "TO", flag: "🇹🇴", phoneCode: "+676", totalLength: 10 },
  { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹", phoneCode: "+1-868", totalLength: 11 },
  { name: "Tunisia", code: "TN", flag: "🇹🇳", phoneCode: "+216", totalLength: 12 },
  { name: "Turkey", code: "TR", flag: "🇹🇷", phoneCode: "+90", totalLength: 12 },
  { name: "Turkmenistan", code: "TM", flag: "🇹🇲", phoneCode: "+993", totalLength: 11 },
  { name: "Tuvalu", code: "TV", flag: "🇹🇻", phoneCode: "+688", totalLength: 7 },
  { name: "Uganda", code: "UG", flag: "🇺🇬", phoneCode: "+256", totalLength: 12 },
  { name: "Ukraine", code: "UA", flag: "🇺🇦", phoneCode: "+380", totalLength: 12 },
  { name: "United Arab Emirates (UAE)", code: "AE", flag: "🇦🇪", phoneCode: "+971", totalLength: 12 },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧", phoneCode: "+44", totalLength: 12 },
  { name: "United States", code: "US", flag: "🇺🇸", phoneCode: "+1", totalLength: 11 },
  { name: "Uruguay", code: "UY", flag: "🇺🇾", phoneCode: "+598", totalLength: 11 },
  { name: "Uzbekistan", code: "UZ", flag: "🇺🇿", phoneCode: "+998", totalLength: 12 },
  { name: "Vanuatu", code: "VU", flag: "🇻🇺", phoneCode: "+678", totalLength: 7 },
  { name: "Venezuela", code: "VE", flag: "🇻🇪", phoneCode: "+58", totalLength: 12 },
  { name: "Vietnam", code: "VN", flag: "🇻🇳", phoneCode: "+84", totalLength: 11 },
  { name: "Yemen", code: "YE", flag: "🇾🇪", phoneCode: "+967", totalLength: 11 },
  { name: "Zambia", code: "ZM", flag: "🇿🇲", phoneCode: "+260", totalLength: 10 },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼", phoneCode: "+263", totalLength: 10 },
  { name: "Taiwan (ROC)", code: "TW", flag: "🇹🇼", phoneCode: "+886", totalLength: 12 },
  { name: "Kosovo", code: "XK", flag: "🇽🇰", phoneCode: "+383", totalLength: 12 },
  { name: "Western Sahara (SADR)", code: "EH", flag: "🇪🇭", phoneCode: "+212", totalLength: 12 },
  { name: "Abkhazia", code: "AB", flag: "🇦🇧", phoneCode: "+995", totalLength: 12 },
  { name: "South Ossetia", code: "OS", flag: "🇴🇸", phoneCode: "+995", totalLength: 12 },
  { name: "Northern Cyprus (TRNC)", code: "NC", flag: "🇹🇷", phoneCode: "+90", totalLength: 12 },
  { name: "Somaliland", code: "SO", flag: "🇸🇴", phoneCode: "+252", totalLength: 9 },
  { name: "Cook Islands", code: "CK", flag: "🇨🇰", phoneCode: "+682", totalLength: 7 },
  { name: "Puerto Rico", code: "PR", flag: "🇵🇷", phoneCode: "+1-787", totalLength: 11 },
  { name: "Hong Kong", code: "HK", flag: "🇭🇰", phoneCode: "+852", totalLength: 11 },
  { name: "Macao", code: "MO", flag: "🇲🇴", phoneCode: "+853", totalLength: 10 },
  { name: "Guernsey", code: "GG", flag: "🇬🇬", phoneCode: "+44-1481", totalLength: 12 },
  { name: "Jersey", code: "JE", flag: "🇯🇪", phoneCode: "+44-1534", totalLength: 12 },
  { name: "Isle of Man", code: "IM", flag: "🇮🇲", phoneCode: "+44-1624", totalLength: 12 },
  { name: "Gibraltar", code: "GI", flag: "🇬🇮", phoneCode: "+350", totalLength: 9 },
  { name: "Cayman Islands", code: "KY", flag: "🇰🇾", phoneCode: "+1-345", totalLength: 11 },
  { name: "Bermuda", code: "BM", flag: "🇧🇲", phoneCode: "+1-441", totalLength: 11 },
  { name: "Greenland", code: "GL", flag: "🇬🇱", phoneCode: "+299", totalLength: 10 },
  { name: "Curaçao", code: "CW", flag: "🇨🇼", phoneCode: "+599", totalLength: 10 },
  { name: "Aruba", code: "AW", flag: "🇦🇼", phoneCode: "+297", totalLength: 10 }
];

// Helper function to search countries
export const searchCountries = (query) => {
  const lowerQuery = query.toLowerCase();
  return countries.filter(
    (country) =>
      country.name.toLowerCase().includes(lowerQuery) ||
      country.code.toLowerCase().includes(lowerQuery) ||
      country.phoneCode.includes(query)
  );
};

// Helper function to get country by code
export const getCountryByCode = (code) => {
  return countries.find((country) => country.code === code);
};

// Helper function to get country by phone code
export const getCountryByPhoneCode = (phoneCode) => {
  return countries.find((country) => country.phoneCode === phoneCode);
};

